services:
  db:
    image: mysql
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - "./backend/db/initDB.sh:/docker-entrypoint-initdb.d/0_init.sh"
      - "./backend/db/schema.sql:/docker-entrypoint-initdb.d/1.sql"
    networks:
      - matcha
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    env_file:
      - .env
    networks:
      - matcha
    depends_on:
      - db
  # frontend:
  #   build:
  #     context: frontend
  #     dockerfile: ./Dockerfile
  #   networks:
  #     - matcha
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./frontend:/app:rw
  #     - /app/node_modules
  backend:
    build:
      context: backend
      dockerfile: ./Dockerfile
    networks:
      - matcha
    ports:
      - 3001:3001
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

networks:
  matcha:
