// src/services/authService.js
const argon2 = require("argon2");
const jwt = require("jsonwebtoken");
const userService = require("@services/users/users.service");
const generator = require("generate-password");

const JWT_SECRET = process.env.JWT_SECRET || "yourSecretKey";

/**
 * Hashes a given password using Argon2.
 *
 * @param {string} password - The password to hash.
 *
 * @returns {Promise<string>} The hashed password.
 */
async function hashPassword(password) {
  return await argon2.hash(password);
}

/**
 * Verifies a given password against a hash generated by argon2.
 *
 * @param {string} password - The password to verify.
 * @param {string} hash - The hash to verify against.
 *
 * @returns {Promise<boolean>} - true if the password matches, false otherwise.
 */
async function verifyPassword(password, hash) {
  return await argon2.verify(hash, password);
}

/**
 * Generates a JSON Web Token (JWT) for a given user.
 *
 * @param {object} user - The user object containing at least the user's id and email.
 * @returns {string} The generated JWT, signed with a secret and set to expire in 1 hour.
 */
function generateToken(user) {
  return jwt.sign({ id: user.id, email: user.email }, JWT_SECRET, {
    expiresIn: "24h",
  });
}

/**
 * Registers a new user by hashing the given password and creating a new entry in the database
 * @param {object} user - An object with the following fields: firstName, lastName, email, password
 * @returns {object} The newly created user
 * @throws if the user object is invalid
 */
async function registerUser(user) {
  user.password = await hashPassword(user.password);
  const newUser = await userService.create(user);
  const token = generateToken(newUser);
  return { newUser, token };
}

/**
 * Authenticates a user by their email and password, and returns a JWT token to access restricted routes.
 * @param {string} email - The user's email.
 * @param {string} password - The user's password.
 * @returns {object} An object with the following fields: user, token.
 * @throws if the email or password is invalid
 */
async function authenticateUser(email, password) {
  try {
    const users = await userService.findByEmail(email);
    let user;
    if (typeof users === "object") {
      user = users;
    } else user = users[0];
    if (user && (await verifyPassword(password, user.password))) {
      const token = await generateToken(user);
      return { user, token };
    }
    throw new Error("Invalid email or password");
  } catch (error) {
    throw new Error(error.message);
  }
}
/**
 * Finds or creates a user by their GoogleId, email, firstName, and lastName.
 * If the user already exists, return the existing user.
 * If the user does not exist, create a new user with the given information.
 * @param {object} user - An object with the following fields: googleId, email, firstName, lastName.
 * @returns {object} The user object.
 */
async function findOrCreateUser({ email, firstName, lastName }) {
  try {
    const generatedPassword = generator.generate({
      length: 32,
      numbers: true,
      uppercase: true,
      lowercase: true,
    });
    const newUser = await userService.create({
      email,
      firstName,
      lastName,
      lastLocation: "default",
      password: generatedPassword,
    });
    return newUser;
  } catch (error) {
    return await userService.findByEmail(email);
  }
}

function FourtyTwoAuthenticate() {
  return `${process.env.FORTY_API_LINK}/authorize?client_id=${process.env.FORTY_CLIENT_ID}&redirect_uri=${process.env.FORTY_TWO_REDIRECT_URI}&response_type=code`;
}

module.exports = {
  registerUser,
  authenticateUser,
  generateToken,
  findOrCreateUser,
  verifyPassword,
  FourtyTwoAuthenticate,
};
